#! /bin/sh

if [ -z $(ps x | grep 'node chat.ts' | grep -v grep | awk '{print $1}') ];
then
    nohup node chat.ts > log/$(date +"%Y-%m-%d_%H-%M-%S").log 2>&1 &
else
    echo "app is already running"
fi
